In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline
sns.set_theme(style="whitegrid")

In [12]:
#Reads the .csv file
df = pd.read_csv(r"C:\Users\harri\OneDrive\Documents\DataScienceProjects\Retail_Demand_Forecasting_Project\data\demand_forecasting.csv")

#Prints the shape of the dataframe out
df.shape

(76000, 16)

In [13]:
#Shows the data types for the dataset
df.dtypes

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Price                 float64
Discount                int64
Weather Condition      object
Promotion               int64
Competitor Pricing    float64
Seasonality            object
Epidemic                int64
Demand                  int64
dtype: object

In [14]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [ ]:
#Prints out the numeric correlation matrix
numeric_corr = df.corr(numeric_only=True)
numeric_corr

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand
Inventory Level,1.000000,0.234590,-0.034698,-0.036673,-0.000678,-0.006082,-0.034754,-0.097550,0.126618
Units Sold,0.234590,1.000000,0.433943,-0.014506,0.183523,0.227062,-0.013989,-0.317855,0.833421
Units Ordered,-0.034698,0.433943,1.000000,0.044980,0.172972,0.214743,0.045235,-0.100546,0.511963
Price,-0.036673,-0.014506,0.044980,1.000000,-0.094136,-0.043190,0.976648,-0.089658,-0.023461
Discount,-0.000678,0.183523,0.172972,-0.094136,1.000000,0.784039,-0.092066,-0.003885,0.224723
Promotion,-0.006082,0.227062,0.214743,-0.043190,0.784039,1.000000,-0.041385,0.000700,0.282537
Competitor Pricing,-0.034754,-0.013989,0.045235,0.976648,-0.092066,-0.041385,1.000000,-0.089466,-0.023036
Epidemic,-0.097550,-0.317855,-0.100546,-0.089658,-0.003885,0.000700,-0.089466,1.000000,-0.363661
Demand,0.126618,0.833421,0.511963,-0.023461,0.224723,0.282537,-0.023036,-0.363661,1.000000

In [18]:
numeric_features = ['Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Promotion', 'Competitor Pricing', 'Epidemic', 'Demand']
for col in numeric_features:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"{col}: " + str(len(outliers)) + " outliers")

Inventory Level: 2759 outliers
Units Sold: 1411 outliers
Units Ordered: 7524 outliers
Price: 70 outliers
Discount: 12413 outliers
Promotion: 0 outliers
Competitor Pricing: 185 outliers
Epidemic: 15200 outliers
Demand: 986 outliers

In [20]:
#Trying a Spearman Correlation Matrix since massive amount of outliers
df[numeric_features].corr(method='spearman')

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand
Inventory Level,1.000000,0.252028,-0.277970,0.007980,-0.000829,-0.005777,0.010174,-0.106334,0.117184
Units Sold,0.252028,1.000000,0.337778,-0.013064,0.166772,0.211554,-0.012589,-0.341171,0.847304
Units Ordered,-0.277970,0.337778,1.000000,0.024945,0.146276,0.189399,0.024087,-0.075258,0.426569
Price,0.007980,-0.013064,0.024945,1.000000,-0.083128,-0.039252,0.983696,-0.081835,-0.024321
Discount,-0.000829,0.166772,0.146276,-0.083128,1.000000,0.765674,-0.080804,-0.003444,0.204341
Promotion,-0.005777,0.211554,0.189399,-0.039252,0.765674,1.000000,-0.037759,0.000700,0.261325
Competitor Pricing,0.010174,-0.012589,0.024087,0.983696,-0.080804,-0.037759,1.000000,-0.080965,-0.024071
Epidemic,-0.106334,-0.341171,-0.075258,-0.081835,-0.003444,0.000700,-0.080965,1.000000,-0.376951
Demand,0.117184,0.847304,0.426569,-0.024321,0.204341,0.261325,-0.024071,-0.376951,1.000000